config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  # get "/blog_posts/new" , to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id/edit" , to: "blog_posts#edit", as: :edit_blog_post
  # patch "/blog_posts/:id" , to: "blog_posts#update"
  # delete "/blog_posts/:id" , to: "blog_posts#destroy"
  # get "/blog_posts/:id" , to: "blog_posts#show", as: :blog_post
  # post "/blog_posts" , to: "blog_posts#create", as: :blog_posts
  
  resources :blog_posts
  # defines the root path route("/")

  root "blog_posts#index"

   
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_rich_text :content

    validates :title , presence: true
    validates :content , presence: true
    validates :published_at , presence: true

    scope :sorted, -> {order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }
    scope :draft, -> {where(published_at: nil) }
    scope :published, -> {where("published_at <= ?", Time.current)}
    scope :scheduled, -> {where("published_at > ?",Time.current)}

      
    def draft?
        published_at.nil? 
    end

    def published?
    published_at? && published_at <= Time.current
    end
    
    def scheduled?
        published_at? && published_at > Time.current
    end
    

end

 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
     
    before_action :authenticate_user! , except: [:index,:show]
     before_action :set_blog_post , only: [:show,:edit ,:update,:destroy]   
    #  before_action :set_blog_post ,except[:index,:new,:create]  
   
    def index
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
        # just saving all the blogposts in an instance variable
        # rails knows to share those with the erb
    end

     def show
    end


    
    def new
        @blog_post = BlogPost.new
    end
    
    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new , status: :unprocessable_entity
        end
    end
      
  
    
      
    def edit
    end
    
    def update
       
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
         render :edit ,status: :unprocessable_entity
        end
   end

    def destroy
       
        @blog_post.destroy
        redirect_to root_path
    end
 

    

    private
    
    def blog_post_params
        params.require(:blog_post).permit(:title, :content, :published_at)
    end
    
    def set_blog_post
        @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
         rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form |%>
    <% if form.object.errors.any? %>
    <div>
    <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <% end %>
      </div>
     <% end %>
    <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    </div>

    <div>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
    </div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at ,include_blank: true %>
    <div>
    </div>

    <%= form.button %>

<% end %>

 

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete , data: {turbo_confirm:"Are you sure you want to delete this?"}%> 

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>


 

app/views/blog_posts/new.html.erb
<h1>New Blog Posts</h1>

<%= render partial: "form", locals: {blog_post: @blog_post, qwert: 'asdf'} %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit the blog", edit_blog_post_path if user_signed_in?%>
<h1><%= @blog_post.title %></h1>
<%= @blog_post.content %> 

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext",  "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <body class= "prose mx-auto">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <div>
    <% if user_signed_in? %>
    <%= link_to "New Blog Post", new_blog_post_path %>
    <%#= link_to "Profile", edit_user_registration_path %>
    <%= button_to "Log Out", destroy_user_session_path , method: :delete %>
    <%# else %>
    <%#= link_to "Login", new_user_registration_path%>
    <%#= link_to "Sign_Up", new_user_registration_path%>
    <% end %>

    </div>
  
  <%= yield %>
  </body>
</html>

   